server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway    #微服务的名称
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka #eureka集群 
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
    
zuul: 
  prefix: /jean #前缀http://myzuul.com:9527/jean/mydept/
  
  #ignored-services: microservicecloud-dept#忽略真实微服务名称地址http://myzuul.com:9527/microservicecloud-dept/，这个地址就访问不了了
  ignored-services: "*" #希望忽略很多个真实的微服务名称
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**  #http://myzuul.com:9527/mydept/
 
 

 
info:
  app.name: jean-microcloud
  company.name: www.jean.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

